// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: group.proto

package group

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 群组信息
type Group struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	OwnerId        int64                  `protobuf:"varint,5,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MemberCount    int32                  `protobuf:"varint,6,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	MaxMemberCount int32                  `protobuf:"varint,7,opt,name=max_member_count,json=maxMemberCount,proto3" json:"max_member_count,omitempty"`
	Status         int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"` // 1:正常 2:禁用
	CreateAt       int64                  `protobuf:"varint,9,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt       int64                  `protobuf:"varint,10,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Group) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Group) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *Group) GetMaxMemberCount() int32 {
	if x != nil {
		return x.MaxMemberCount
	}
	return 0
}

func (x *Group) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Group) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Group) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// 群组成员
type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"`        // 1:群主 2:管理员 3:普通成员
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"` // 群昵称
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`    // 1:正常 2:禁言
	JoinTime      int64                  `protobuf:"varint,7,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,8,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{1}
}

func (x *GroupMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupMember) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GroupMember) GetJoinTime() int64 {
	if x != nil {
		return x.JoinTime
	}
	return 0
}

func (x *GroupMember) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// 创建群组请求
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	MemberIds     []int64                `protobuf:"varint,5,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateGroupRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// 创建群组响应
type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupResponse) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 加入群组请求
type JoinGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // 申请理由
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupRequest) Reset() {
	*x = JoinGroupRequest{}
	mi := &file_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupRequest) ProtoMessage() {}

func (x *JoinGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupRequest.ProtoReflect.Descriptor instead.
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{4}
}

func (x *JoinGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *JoinGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *JoinGroupRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// 加入群组响应
type JoinGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinGroupResponse) Reset() {
	*x = JoinGroupResponse{}
	mi := &file_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGroupResponse) ProtoMessage() {}

func (x *JoinGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGroupResponse.ProtoReflect.Descriptor instead.
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{5}
}

func (x *JoinGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 邀请加入群组请求
type InviteToGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InviterId     int64                  `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	UserIds       []int64                `protobuf:"varint,3,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToGroupRequest) Reset() {
	*x = InviteToGroupRequest{}
	mi := &file_group_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToGroupRequest) ProtoMessage() {}

func (x *InviteToGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToGroupRequest.ProtoReflect.Descriptor instead.
func (*InviteToGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{6}
}

func (x *InviteToGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *InviteToGroupRequest) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *InviteToGroupRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// 邀请加入群组响应
type InviteToGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FailedUserIds []int64                `protobuf:"varint,3,rep,packed,name=failed_user_ids,json=failedUserIds,proto3" json:"failed_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteToGroupResponse) Reset() {
	*x = InviteToGroupResponse{}
	mi := &file_group_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteToGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteToGroupResponse) ProtoMessage() {}

func (x *InviteToGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteToGroupResponse.ProtoReflect.Descriptor instead.
func (*InviteToGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{7}
}

func (x *InviteToGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InviteToGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InviteToGroupResponse) GetFailedUserIds() []int64 {
	if x != nil {
		return x.FailedUserIds
	}
	return nil
}

// 退出群组请求
type LeaveGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupRequest) Reset() {
	*x = LeaveGroupRequest{}
	mi := &file_group_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupRequest) ProtoMessage() {}

func (x *LeaveGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupRequest.ProtoReflect.Descriptor instead.
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{8}
}

func (x *LeaveGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *LeaveGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 退出群组响应
type LeaveGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveGroupResponse) Reset() {
	*x = LeaveGroupResponse{}
	mi := &file_group_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveGroupResponse) ProtoMessage() {}

func (x *LeaveGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveGroupResponse.ProtoReflect.Descriptor instead.
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 踢出群组请求
type KickFromGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickFromGroupRequest) Reset() {
	*x = KickFromGroupRequest{}
	mi := &file_group_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickFromGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickFromGroupRequest) ProtoMessage() {}

func (x *KickFromGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickFromGroupRequest.ProtoReflect.Descriptor instead.
func (*KickFromGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{10}
}

func (x *KickFromGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *KickFromGroupRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *KickFromGroupRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 踢出群组响应
type KickFromGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickFromGroupResponse) Reset() {
	*x = KickFromGroupResponse{}
	mi := &file_group_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickFromGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickFromGroupResponse) ProtoMessage() {}

func (x *KickFromGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickFromGroupResponse.ProtoReflect.Descriptor instead.
func (*KickFromGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{11}
}

func (x *KickFromGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KickFromGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取群组信息请求
type GetGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupInfoRequest) Reset() {
	*x = GetGroupInfoRequest{}
	mi := &file_group_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoRequest) ProtoMessage() {}

func (x *GetGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 获取群组信息响应
type GetGroupInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo      *Group                 `protobuf:"bytes,1,opt,name=group_info,json=groupInfo,proto3" json:"group_info,omitempty"`
	UserMemberInfo *GroupMember           `protobuf:"bytes,2,opt,name=user_member_info,json=userMemberInfo,proto3" json:"user_member_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGroupInfoResponse) Reset() {
	*x = GetGroupInfoResponse{}
	mi := &file_group_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupInfoResponse) ProtoMessage() {}

func (x *GetGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GetGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{13}
}

func (x *GetGroupInfoResponse) GetGroupInfo() *Group {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

func (x *GetGroupInfoResponse) GetUserMemberInfo() *GroupMember {
	if x != nil {
		return x.UserMemberInfo
	}
	return nil
}

// 获取群组列表请求
type GetGroupListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupListRequest) Reset() {
	*x = GetGroupListRequest{}
	mi := &file_group_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupListRequest) ProtoMessage() {}

func (x *GetGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupListRequest.ProtoReflect.Descriptor instead.
func (*GetGroupListRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{14}
}

func (x *GetGroupListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGroupListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取群组列表响应
type GetGroupListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupListResponse) Reset() {
	*x = GetGroupListResponse{}
	mi := &file_group_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupListResponse) ProtoMessage() {}

func (x *GetGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupListResponse.ProtoReflect.Descriptor instead.
func (*GetGroupListResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{15}
}

func (x *GetGroupListResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetGroupListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 获取群组成员列表请求
type GetGroupMemberListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 请求者ID，用于权限验证
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListRequest) Reset() {
	*x = GetGroupMemberListRequest{}
	mi := &file_group_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListRequest) ProtoMessage() {}

func (x *GetGroupMemberListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListRequest.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupMemberListRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetGroupMemberListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGroupMemberListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGroupMemberListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 获取群组成员列表响应
type GetGroupMemberListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*GroupMember         `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMemberListResponse) Reset() {
	*x = GetGroupMemberListResponse{}
	mi := &file_group_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMemberListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMemberListResponse) ProtoMessage() {}

func (x *GetGroupMemberListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMemberListResponse.ProtoReflect.Descriptor instead.
func (*GetGroupMemberListResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{17}
}

func (x *GetGroupMemberListResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GetGroupMemberListResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 更新群组信息请求
type UpdateGroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoRequest) Reset() {
	*x = UpdateGroupInfoRequest{}
	mi := &file_group_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoRequest) ProtoMessage() {}

func (x *UpdateGroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateGroupInfoRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupInfoRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *UpdateGroupInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupInfoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateGroupInfoRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 更新群组信息响应
type UpdateGroupInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupInfoResponse) Reset() {
	*x = UpdateGroupInfoResponse{}
	mi := &file_group_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupInfoResponse) ProtoMessage() {}

func (x *UpdateGroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateGroupInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateGroupInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 设置群组成员角色请求
type SetMemberRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"` // 2:管理员 3:普通成员
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRoleRequest) Reset() {
	*x = SetMemberRoleRequest{}
	mi := &file_group_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRoleRequest) ProtoMessage() {}

func (x *SetMemberRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRoleRequest.ProtoReflect.Descriptor instead.
func (*SetMemberRoleRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{20}
}

func (x *SetMemberRoleRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SetMemberRoleRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *SetMemberRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetMemberRoleRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

// 设置群组成员角色响应
type SetMemberRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMemberRoleResponse) Reset() {
	*x = SetMemberRoleResponse{}
	mi := &file_group_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMemberRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMemberRoleResponse) ProtoMessage() {}

func (x *SetMemberRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMemberRoleResponse.ProtoReflect.Descriptor instead.
func (*SetMemberRoleResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{21}
}

func (x *SetMemberRoleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetMemberRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 禁言群组成员请求
type MuteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OperatorId    int64                  `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Duration      int64                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"` // 禁言时长(秒)，0表示取消禁言
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberRequest) Reset() {
	*x = MuteMemberRequest{}
	mi := &file_group_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberRequest) ProtoMessage() {}

func (x *MuteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberRequest.ProtoReflect.Descriptor instead.
func (*MuteMemberRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{22}
}

func (x *MuteMemberRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MuteMemberRequest) GetOperatorId() int64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *MuteMemberRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MuteMemberRequest) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// 禁言群组成员响应
type MuteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MuteMemberResponse) Reset() {
	*x = MuteMemberResponse{}
	mi := &file_group_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MuteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuteMemberResponse) ProtoMessage() {}

func (x *MuteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuteMemberResponse.ProtoReflect.Descriptor instead.
func (*MuteMemberResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{23}
}

func (x *MuteMemberResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MuteMemberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 解散群组请求
type DismissGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupRequest) Reset() {
	*x = DismissGroupRequest{}
	mi := &file_group_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupRequest) ProtoMessage() {}

func (x *DismissGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupRequest.ProtoReflect.Descriptor instead.
func (*DismissGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{24}
}

func (x *DismissGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DismissGroupRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

// 解散群组响应
type DismissGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissGroupResponse) Reset() {
	*x = DismissGroupResponse{}
	mi := &file_group_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissGroupResponse) ProtoMessage() {}

func (x *DismissGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissGroupResponse.ProtoReflect.Descriptor instead.
func (*DismissGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{25}
}

func (x *DismissGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DismissGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 转让群组请求
type TransferGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	NewOwnerId    int64                  `protobuf:"varint,3,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferGroupRequest) Reset() {
	*x = TransferGroupRequest{}
	mi := &file_group_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferGroupRequest) ProtoMessage() {}

func (x *TransferGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferGroupRequest.ProtoReflect.Descriptor instead.
func (*TransferGroupRequest) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{26}
}

func (x *TransferGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TransferGroupRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *TransferGroupRequest) GetNewOwnerId() int64 {
	if x != nil {
		return x.NewOwnerId
	}
	return 0
}

// 转让群组响应
type TransferGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferGroupResponse) Reset() {
	*x = TransferGroupResponse{}
	mi := &file_group_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferGroupResponse) ProtoMessage() {}

func (x *TransferGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_group_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferGroupResponse.ProtoReflect.Descriptor instead.
func (*TransferGroupResponse) Descriptor() ([]byte, []int) {
	return file_group_proto_rawDescGZIP(), []int{27}
}

func (x *TransferGroupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferGroupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_group_proto protoreflect.FileDescriptor

const file_group_proto_rawDesc = "" +
	"\n" +
	"\vgroup.proto\x12\x05group\"\x9f\x02\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x19\n" +
	"\bowner_id\x18\x05 \x01(\x03R\aownerId\x12!\n" +
	"\fmember_count\x18\x06 \x01(\x05R\vmemberCount\x12(\n" +
	"\x10max_member_count\x18\a \x01(\x05R\x0emaxMemberCount\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\x12\x1b\n" +
	"\tcreate_at\x18\t \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tupdate_at\x18\n" +
	" \x01(\x03R\bupdateAt\"\xd3\x01\n" +
	"\vGroupMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1b\n" +
	"\tjoin_time\x18\a \x01(\x03R\bjoinTime\x12\x1b\n" +
	"\tupdate_at\x18\b \x01(\x03R\bupdateAt\"\x9c\x01\n" +
	"\x12CreateGroupRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\x03R\tmemberIds\"d\n" +
	"\x13CreateGroupResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"^\n" +
	"\x10JoinGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"G\n" +
	"\x11JoinGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x14InviteToGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\x03R\tinviterId\x12\x19\n" +
	"\buser_ids\x18\x03 \x03(\x03R\auserIds\"s\n" +
	"\x15InviteToGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12&\n" +
	"\x0ffailed_user_ids\x18\x03 \x03(\x03R\rfailedUserIds\"G\n" +
	"\x11LeaveGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"H\n" +
	"\x12LeaveGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"k\n" +
	"\x14KickFromGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"K\n" +
	"\x15KickFromGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x13GetGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"\x81\x01\n" +
	"\x14GetGroupInfoResponse\x12+\n" +
	"\n" +
	"group_info\x18\x01 \x01(\v2\f.group.GroupR\tgroupInfo\x12<\n" +
	"\x10user_member_info\x18\x02 \x01(\v2\x12.group.GroupMemberR\x0euserMemberInfo\"_\n" +
	"\x13GetGroupListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"R\n" +
	"\x14GetGroupListResponse\x12$\n" +
	"\x06groups\x18\x01 \x03(\v2\f.group.GroupR\x06groups\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x80\x01\n" +
	"\x19GetGroupMemberListRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"`\n" +
	"\x1aGetGroupMemberListResponse\x12,\n" +
	"\amembers\x18\x01 \x03(\v2\x12.group.GroupMemberR\amembers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xa2\x01\n" +
	"\x16UpdateGroupInfoRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"M\n" +
	"\x17UpdateGroupInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x7f\n" +
	"\x14SetMemberRoleRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"K\n" +
	"\x15SetMemberRoleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x84\x01\n" +
	"\x11MuteMemberRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x03R\n" +
	"operatorId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x03R\bduration\"H\n" +
	"\x12MuteMemberResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x13DismissGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\"J\n" +
	"\x14DismissGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x14TransferGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12 \n" +
	"\fnew_owner_id\x18\x03 \x01(\x03R\n" +
	"newOwnerId\"K\n" +
	"\x15TransferGroupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd2\a\n" +
	"\fGroupService\x12D\n" +
	"\vCreateGroup\x12\x19.group.CreateGroupRequest\x1a\x1a.group.CreateGroupResponse\x12>\n" +
	"\tJoinGroup\x12\x17.group.JoinGroupRequest\x1a\x18.group.JoinGroupResponse\x12J\n" +
	"\rInviteToGroup\x12\x1b.group.InviteToGroupRequest\x1a\x1c.group.InviteToGroupResponse\x12A\n" +
	"\n" +
	"LeaveGroup\x12\x18.group.LeaveGroupRequest\x1a\x19.group.LeaveGroupResponse\x12J\n" +
	"\rKickFromGroup\x12\x1b.group.KickFromGroupRequest\x1a\x1c.group.KickFromGroupResponse\x12G\n" +
	"\fGetGroupInfo\x12\x1a.group.GetGroupInfoRequest\x1a\x1b.group.GetGroupInfoResponse\x12G\n" +
	"\fGetGroupList\x12\x1a.group.GetGroupListRequest\x1a\x1b.group.GetGroupListResponse\x12Y\n" +
	"\x12GetGroupMemberList\x12 .group.GetGroupMemberListRequest\x1a!.group.GetGroupMemberListResponse\x12P\n" +
	"\x0fUpdateGroupInfo\x12\x1d.group.UpdateGroupInfoRequest\x1a\x1e.group.UpdateGroupInfoResponse\x12J\n" +
	"\rSetMemberRole\x12\x1b.group.SetMemberRoleRequest\x1a\x1c.group.SetMemberRoleResponse\x12A\n" +
	"\n" +
	"MuteMember\x12\x18.group.MuteMemberRequest\x1a\x19.group.MuteMemberResponse\x12G\n" +
	"\fDismissGroup\x12\x1a.group.DismissGroupRequest\x1a\x1b.group.DismissGroupResponse\x12J\n" +
	"\rTransferGroup\x12\x1b.group.TransferGroupRequest\x1a\x1c.group.TransferGroupResponseB\tZ\a./groupb\x06proto3"

var (
	file_group_proto_rawDescOnce sync.Once
	file_group_proto_rawDescData []byte
)

func file_group_proto_rawDescGZIP() []byte {
	file_group_proto_rawDescOnce.Do(func() {
		file_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)))
	})
	return file_group_proto_rawDescData
}

var file_group_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_group_proto_goTypes = []any{
	(*Group)(nil),                      // 0: group.Group
	(*GroupMember)(nil),                // 1: group.GroupMember
	(*CreateGroupRequest)(nil),         // 2: group.CreateGroupRequest
	(*CreateGroupResponse)(nil),        // 3: group.CreateGroupResponse
	(*JoinGroupRequest)(nil),           // 4: group.JoinGroupRequest
	(*JoinGroupResponse)(nil),          // 5: group.JoinGroupResponse
	(*InviteToGroupRequest)(nil),       // 6: group.InviteToGroupRequest
	(*InviteToGroupResponse)(nil),      // 7: group.InviteToGroupResponse
	(*LeaveGroupRequest)(nil),          // 8: group.LeaveGroupRequest
	(*LeaveGroupResponse)(nil),         // 9: group.LeaveGroupResponse
	(*KickFromGroupRequest)(nil),       // 10: group.KickFromGroupRequest
	(*KickFromGroupResponse)(nil),      // 11: group.KickFromGroupResponse
	(*GetGroupInfoRequest)(nil),        // 12: group.GetGroupInfoRequest
	(*GetGroupInfoResponse)(nil),       // 13: group.GetGroupInfoResponse
	(*GetGroupListRequest)(nil),        // 14: group.GetGroupListRequest
	(*GetGroupListResponse)(nil),       // 15: group.GetGroupListResponse
	(*GetGroupMemberListRequest)(nil),  // 16: group.GetGroupMemberListRequest
	(*GetGroupMemberListResponse)(nil), // 17: group.GetGroupMemberListResponse
	(*UpdateGroupInfoRequest)(nil),     // 18: group.UpdateGroupInfoRequest
	(*UpdateGroupInfoResponse)(nil),    // 19: group.UpdateGroupInfoResponse
	(*SetMemberRoleRequest)(nil),       // 20: group.SetMemberRoleRequest
	(*SetMemberRoleResponse)(nil),      // 21: group.SetMemberRoleResponse
	(*MuteMemberRequest)(nil),          // 22: group.MuteMemberRequest
	(*MuteMemberResponse)(nil),         // 23: group.MuteMemberResponse
	(*DismissGroupRequest)(nil),        // 24: group.DismissGroupRequest
	(*DismissGroupResponse)(nil),       // 25: group.DismissGroupResponse
	(*TransferGroupRequest)(nil),       // 26: group.TransferGroupRequest
	(*TransferGroupResponse)(nil),      // 27: group.TransferGroupResponse
}
var file_group_proto_depIdxs = []int32{
	0,  // 0: group.GetGroupInfoResponse.group_info:type_name -> group.Group
	1,  // 1: group.GetGroupInfoResponse.user_member_info:type_name -> group.GroupMember
	0,  // 2: group.GetGroupListResponse.groups:type_name -> group.Group
	1,  // 3: group.GetGroupMemberListResponse.members:type_name -> group.GroupMember
	2,  // 4: group.GroupService.CreateGroup:input_type -> group.CreateGroupRequest
	4,  // 5: group.GroupService.JoinGroup:input_type -> group.JoinGroupRequest
	6,  // 6: group.GroupService.InviteToGroup:input_type -> group.InviteToGroupRequest
	8,  // 7: group.GroupService.LeaveGroup:input_type -> group.LeaveGroupRequest
	10, // 8: group.GroupService.KickFromGroup:input_type -> group.KickFromGroupRequest
	12, // 9: group.GroupService.GetGroupInfo:input_type -> group.GetGroupInfoRequest
	14, // 10: group.GroupService.GetGroupList:input_type -> group.GetGroupListRequest
	16, // 11: group.GroupService.GetGroupMemberList:input_type -> group.GetGroupMemberListRequest
	18, // 12: group.GroupService.UpdateGroupInfo:input_type -> group.UpdateGroupInfoRequest
	20, // 13: group.GroupService.SetMemberRole:input_type -> group.SetMemberRoleRequest
	22, // 14: group.GroupService.MuteMember:input_type -> group.MuteMemberRequest
	24, // 15: group.GroupService.DismissGroup:input_type -> group.DismissGroupRequest
	26, // 16: group.GroupService.TransferGroup:input_type -> group.TransferGroupRequest
	3,  // 17: group.GroupService.CreateGroup:output_type -> group.CreateGroupResponse
	5,  // 18: group.GroupService.JoinGroup:output_type -> group.JoinGroupResponse
	7,  // 19: group.GroupService.InviteToGroup:output_type -> group.InviteToGroupResponse
	9,  // 20: group.GroupService.LeaveGroup:output_type -> group.LeaveGroupResponse
	11, // 21: group.GroupService.KickFromGroup:output_type -> group.KickFromGroupResponse
	13, // 22: group.GroupService.GetGroupInfo:output_type -> group.GetGroupInfoResponse
	15, // 23: group.GroupService.GetGroupList:output_type -> group.GetGroupListResponse
	17, // 24: group.GroupService.GetGroupMemberList:output_type -> group.GetGroupMemberListResponse
	19, // 25: group.GroupService.UpdateGroupInfo:output_type -> group.UpdateGroupInfoResponse
	21, // 26: group.GroupService.SetMemberRole:output_type -> group.SetMemberRoleResponse
	23, // 27: group.GroupService.MuteMember:output_type -> group.MuteMemberResponse
	25, // 28: group.GroupService.DismissGroup:output_type -> group.DismissGroupResponse
	27, // 29: group.GroupService.TransferGroup:output_type -> group.TransferGroupResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_group_proto_init() }
func file_group_proto_init() {
	if File_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_proto_rawDesc), len(file_group_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_group_proto_goTypes,
		DependencyIndexes: file_group_proto_depIdxs,
		MessageInfos:      file_group_proto_msgTypes,
	}.Build()
	File_group_proto = out.File
	file_group_proto_goTypes = nil
	file_group_proto_depIdxs = nil
}
