version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: im_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_CLUSTER=etcd=http://etcd:2380
      - ETCD_NAME=etcd
      - ETCD_DATA_DIR=/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"

  im-service:
    build: .
    ports:
      - "10001:10001"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - etcd
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - ETCD_HOST=etcd

volumes:
  mysql_data: