FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./pkg ./pkg
COPY ./rpc/friend ./rpc/friend

RUN CGO_ENABLED=0 GOOS=linux go build -o friend-rpc ./rpc/friend

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/friend-rpc .
COPY rpc/friend/etc ./etc

EXPOSE 10000

ENTRYPOINT ["./friend-rpc"]
