FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./pkg ./pkg
COPY ./rpc/file ./rpc/file

RUN CGO_ENABLED=0 GOOS=linux go build -o file-rpc ./rpc/file

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/file-rpc .
COPY rpc/file/etc ./etc

EXPOSE 10000

ENTRYPOINT ["./file-rpc"]
