FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./pkg ./pkg
COPY ./rpc/group ./rpc/group

RUN CGO_ENABLED=0 GOOS=linux go build -o group-rpc ./rpc/group

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/group-rpc .
COPY rpc/group/etc ./etc

EXPOSE 10000

ENTRYPOINT ["./group-rpc"]
