FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./pkg ./pkg
COPY ./api ./api
COPY ./cmd ./cmd
COPY ./rpc ./rpc

RUN CGO_ENABLED=0 GOOS=linux go build -o web-api ./cmd

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/web-api .

EXPOSE 8080

ENTRYPOINT ["./web-api"]