FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./pkg ./pkg
COPY ./rpc/user ./rpc/user

RUN CGO_ENABLED=0 GOOS=linux go build -o user-rpc ./rpc/user

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/user-rpc .
COPY rpc/user/etc ./etc

EXPOSE 10000

ENTRYPOINT ["./user-rpc"]
