FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./pkg ./pkg
COPY ./rpc/message ./rpc/message

RUN CGO_ENABLED=0 GOOS=linux go build -o message-rpc ./rpc/message

FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/message-rpc .
COPY rpc/message/etc ./etc

EXPOSE 10000

ENTRYPOINT ["./message-rpc"]
