// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: idl/contact/contact.proto

package contact

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 联系人列表接口请求参数
type ContactListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListRequest) Reset() {
	*x = ContactListRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListRequest) ProtoMessage() {}

func (x *ContactListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListRequest.ProtoReflect.Descriptor instead.
func (*ContactListRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{0}
}

// 联系人列表接口响应参数
type ContactListResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*ContactListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListResponse) Reset() {
	*x = ContactListResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse) ProtoMessage() {}

func (x *ContactListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse.ProtoReflect.Descriptor instead.
func (*ContactListResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{1}
}

func (x *ContactListResponse) GetItems() []*ContactListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 删除联系人
type ContactDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int32                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDeleteRequest) Reset() {
	*x = ContactDeleteRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDeleteRequest) ProtoMessage() {}

func (x *ContactDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContactDeleteRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{2}
}

func (x *ContactDeleteRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type ContactDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDeleteResponse) Reset() {
	*x = ContactDeleteResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDeleteResponse) ProtoMessage() {}

func (x *ContactDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDeleteResponse.ProtoReflect.Descriptor instead.
func (*ContactDeleteResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{3}
}

// 联系人详情
type ContactDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int32                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDetailRequest) Reset() {
	*x = ContactDetailRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetailRequest) ProtoMessage() {}

func (x *ContactDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetailRequest.ProtoReflect.Descriptor instead.
func (*ContactDetailRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{4}
}

func (x *ContactDetailRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type ContactDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Motto         string                 `protobuf:"bytes,5,opt,name=motto,proto3" json:"motto,omitempty"`
	Gender        int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Relation      int32                  `protobuf:"varint,7,opt,name=relation,proto3" json:"relation,omitempty"` // [0:陌生人;1:好友;...]
	GroupId       int32                  `protobuf:"varint,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Birthday      string                 `protobuf:"bytes,9,opt,name=birthday,proto3" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDetailResponse) Reset() {
	*x = ContactDetailResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetailResponse) ProtoMessage() {}

func (x *ContactDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetailResponse.ProtoReflect.Descriptor instead.
func (*ContactDetailResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{5}
}

func (x *ContactDetailResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactDetailResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactDetailResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactDetailResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactDetailResponse) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *ContactDetailResponse) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactDetailResponse) GetRelation() int32 {
	if x != nil {
		return x.Relation
	}
	return 0
}

func (x *ContactDetailResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ContactDetailResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

// 联系人搜索
type ContactSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactSearchRequest) Reset() {
	*x = ContactSearchRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactSearchRequest) ProtoMessage() {}

func (x *ContactSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactSearchRequest.ProtoReflect.Descriptor instead.
func (*ContactSearchRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{6}
}

func (x *ContactSearchRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type ContactSearchResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Items         []*ContactSearchResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactSearchResponse) Reset() {
	*x = ContactSearchResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactSearchResponse) ProtoMessage() {}

func (x *ContactSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactSearchResponse.ProtoReflect.Descriptor instead.
func (*ContactSearchResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{7}
}

func (x *ContactSearchResponse) GetItems() []*ContactSearchResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 更换联系人分组
type ContactChangeGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int32                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	GroupId       int32                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactChangeGroupRequest) Reset() {
	*x = ContactChangeGroupRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactChangeGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactChangeGroupRequest) ProtoMessage() {}

func (x *ContactChangeGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactChangeGroupRequest.ProtoReflect.Descriptor instead.
func (*ContactChangeGroupRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{8}
}

func (x *ContactChangeGroupRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ContactChangeGroupRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ContactChangeGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactChangeGroupResponse) Reset() {
	*x = ContactChangeGroupResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactChangeGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactChangeGroupResponse) ProtoMessage() {}

func (x *ContactChangeGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactChangeGroupResponse.ProtoReflect.Descriptor instead.
func (*ContactChangeGroupResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{9}
}

// 创建好友申请
type ContactApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      int32                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyRequest) Reset() {
	*x = ContactApplyRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyRequest) ProtoMessage() {}

func (x *ContactApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{10}
}

func (x *ContactApplyRequest) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ContactApplyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContactApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyResponse) Reset() {
	*x = ContactApplyResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyResponse) ProtoMessage() {}

func (x *ContactApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{11}
}

// 同意好友申请
type ContactAgreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactAgreeRequest) Reset() {
	*x = ContactAgreeRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactAgreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactAgreeRequest) ProtoMessage() {}

func (x *ContactAgreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactAgreeRequest.ProtoReflect.Descriptor instead.
func (*ContactAgreeRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{12}
}

func (x *ContactAgreeRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

type ContactAgreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactAgreeResponse) Reset() {
	*x = ContactAgreeResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactAgreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactAgreeResponse) ProtoMessage() {}

func (x *ContactAgreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactAgreeResponse.ProtoReflect.Descriptor instead.
func (*ContactAgreeResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{13}
}

// 拒绝好友申请
type ContactRejectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	Remark        string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactRejectRequest) Reset() {
	*x = ContactRejectRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRejectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRejectRequest) ProtoMessage() {}

func (x *ContactRejectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRejectRequest.ProtoReflect.Descriptor instead.
func (*ContactRejectRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{14}
}

func (x *ContactRejectRequest) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *ContactRejectRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ContactRejectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactRejectResponse) Reset() {
	*x = ContactRejectResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactRejectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactRejectResponse) ProtoMessage() {}

func (x *ContactRejectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactRejectResponse.ProtoReflect.Descriptor instead.
func (*ContactRejectResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{15}
}

// 申请列表
type ContactApplyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyListRequest) Reset() {
	*x = ContactApplyListRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyListRequest) ProtoMessage() {}

func (x *ContactApplyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyListRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyListRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{16}
}

type ContactApplyListResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*ContactApplyListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyListResponse) Reset() {
	*x = ContactApplyListResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyListResponse) ProtoMessage() {}

func (x *ContactApplyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyListResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyListResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{17}
}

func (x *ContactApplyListResponse) GetItems() []*ContactApplyListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 未读申请数
type ContactApplyUnreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyUnreadRequest) Reset() {
	*x = ContactApplyUnreadRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyUnreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyUnreadRequest) ProtoMessage() {}

func (x *ContactApplyUnreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyUnreadRequest.ProtoReflect.Descriptor instead.
func (*ContactApplyUnreadRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{18}
}

type ContactApplyUnreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyUnreadResponse) Reset() {
	*x = ContactApplyUnreadResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyUnreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyUnreadResponse) ProtoMessage() {}

func (x *ContactApplyUnreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyUnreadResponse.ProtoReflect.Descriptor instead.
func (*ContactApplyUnreadResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{19}
}

func (x *ContactApplyUnreadResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 创建分组
type ContactGroupCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 分组名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupCreateRequest) Reset() {
	*x = ContactGroupCreateRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupCreateRequest) ProtoMessage() {}

func (x *ContactGroupCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupCreateRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupCreateRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{20}
}

func (x *ContactGroupCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContactGroupCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 新分组ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupCreateResponse) Reset() {
	*x = ContactGroupCreateResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupCreateResponse) ProtoMessage() {}

func (x *ContactGroupCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupCreateResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupCreateResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{21}
}

func (x *ContactGroupCreateResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// 更新分组
type ContactGroupUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 分组ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // 新分组名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupUpdateRequest) Reset() {
	*x = ContactGroupUpdateRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupUpdateRequest) ProtoMessage() {}

func (x *ContactGroupUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupUpdateRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupUpdateRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{22}
}

func (x *ContactGroupUpdateRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ContactGroupUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ContactGroupUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupUpdateResponse) Reset() {
	*x = ContactGroupUpdateResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupUpdateResponse) ProtoMessage() {}

func (x *ContactGroupUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupUpdateResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupUpdateResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{23}
}

// 删除分组
type ContactGroupDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 分组ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupDeleteRequest) Reset() {
	*x = ContactGroupDeleteRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupDeleteRequest) ProtoMessage() {}

func (x *ContactGroupDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupDeleteRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{24}
}

func (x *ContactGroupDeleteRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ContactGroupDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupDeleteResponse) Reset() {
	*x = ContactGroupDeleteResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupDeleteResponse) ProtoMessage() {}

func (x *ContactGroupDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupDeleteResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupDeleteResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{25}
}

// 联系人分组列表
type ContactGroupListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupListRequest) Reset() {
	*x = ContactGroupListRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupListRequest) ProtoMessage() {}

func (x *ContactGroupListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupListRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupListRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{26}
}

type ContactGroupListResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Items         []*ContactGroupListResponse_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupListResponse) Reset() {
	*x = ContactGroupListResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupListResponse) ProtoMessage() {}

func (x *ContactGroupListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupListResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupListResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{27}
}

func (x *ContactGroupListResponse) GetItems() []*ContactGroupListResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

// 联系人分组详情
type ContactGroupDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 分组ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupDetailRequest) Reset() {
	*x = ContactGroupDetailRequest{}
	mi := &file_idl_contact_contact_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupDetailRequest) ProtoMessage() {}

func (x *ContactGroupDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupDetailRequest.ProtoReflect.Descriptor instead.
func (*ContactGroupDetailRequest) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{28}
}

func (x *ContactGroupDetailRequest) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ContactGroupDetailResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	GroupId       int32                       `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 分组ID
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // 分组名称
	Count         int32                       `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                    // 联系人数
	Contacts      []*ContactListResponse_Item `protobuf:"bytes,4,rep,name=contacts,proto3" json:"contacts,omitempty"`               // 联系人列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupDetailResponse) Reset() {
	*x = ContactGroupDetailResponse{}
	mi := &file_idl_contact_contact_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupDetailResponse) ProtoMessage() {}

func (x *ContactGroupDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupDetailResponse.ProtoReflect.Descriptor instead.
func (*ContactGroupDetailResponse) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{29}
}

func (x *ContactGroupDetailResponse) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ContactGroupDetailResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactGroupDetailResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ContactGroupDetailResponse) GetContacts() []*ContactListResponse_Item {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type ContactListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // 用户ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                             // 用户名
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`                             // 昵称
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                                // 性别[0:未知;1:男;2:女;]
	Motto         string                 `protobuf:"bytes,5,opt,name=motto,proto3" json:"motto,omitempty"`                                   // 座右铭
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                                 // 头像
	GroupId       int32                  `protobuf:"varint,7,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`               // 联系人分组ID
	OnlineStatus  string                 `protobuf:"bytes,8,opt,name=online_status,json=onlineStatus,proto3" json:"online_status,omitempty"` // 在线状态[0:离线;1:在线;...]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactListResponse_Item) Reset() {
	*x = ContactListResponse_Item{}
	mi := &file_idl_contact_contact_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactListResponse_Item) ProtoMessage() {}

func (x *ContactListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactListResponse_Item) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ContactListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactListResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactListResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactListResponse_Item) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

func (x *ContactListResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ContactListResponse_Item) GetOnlineStatus() string {
	if x != nil {
		return x.OnlineStatus
	}
	return ""
}

type ContactSearchResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Motto         string                 `protobuf:"bytes,6,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactSearchResponse_Item) Reset() {
	*x = ContactSearchResponse_Item{}
	mi := &file_idl_contact_contact_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactSearchResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactSearchResponse_Item) ProtoMessage() {}

func (x *ContactSearchResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactSearchResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactSearchResponse_Item) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ContactSearchResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactSearchResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactSearchResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactSearchResponse_Item) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ContactSearchResponse_Item) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *ContactSearchResponse_Item) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type ContactApplyListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       int32                  `protobuf:"varint,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int32                  `protobuf:"varint,3,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ApplyTime     string                 `protobuf:"bytes,7,opt,name=apply_time,json=applyTime,proto3" json:"apply_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactApplyListResponse_Item) Reset() {
	*x = ContactApplyListResponse_Item{}
	mi := &file_idl_contact_contact_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactApplyListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactApplyListResponse_Item) ProtoMessage() {}

func (x *ContactApplyListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactApplyListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactApplyListResponse_Item) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{17, 0}
}

func (x *ContactApplyListResponse_Item) GetApplyId() int32 {
	if x != nil {
		return x.ApplyId
	}
	return 0
}

func (x *ContactApplyListResponse_Item) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ContactApplyListResponse_Item) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *ContactApplyListResponse_Item) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContactApplyListResponse_Item) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ContactApplyListResponse_Item) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ContactApplyListResponse_Item) GetApplyTime() string {
	if x != nil {
		return x.ApplyTime
	}
	return ""
}

type ContactGroupListResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int32                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 分组ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                       // 分组名称
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`                    // 联系人数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactGroupListResponse_Item) Reset() {
	*x = ContactGroupListResponse_Item{}
	mi := &file_idl_contact_contact_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactGroupListResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactGroupListResponse_Item) ProtoMessage() {}

func (x *ContactGroupListResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_idl_contact_contact_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactGroupListResponse_Item.ProtoReflect.Descriptor instead.
func (*ContactGroupListResponse_Item) Descriptor() ([]byte, []int) {
	return file_idl_contact_contact_proto_rawDescGZIP(), []int{27, 0}
}

func (x *ContactGroupListResponse_Item) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ContactGroupListResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContactGroupListResponse_Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_idl_contact_contact_proto protoreflect.FileDescriptor

const file_idl_contact_contact_proto_rawDesc = "" +
	"\n" +
	"\x19idl/contact/contact.proto\x12\acontact\"\x14\n" +
	"\x12ContactListRequest\"\xae\x02\n" +
	"\x13ContactListResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.contact.ContactListResponse.ItemR\x05items\x1a\xdd\x01\n" +
	"\x04Item\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05motto\x18\x05 \x01(\tR\x05motto\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x19\n" +
	"\bgroup_id\x18\a \x01(\x05R\agroupId\x12#\n" +
	"\ronline_status\x18\b \x01(\tR\fonlineStatus\"3\n" +
	"\x14ContactDeleteRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x05R\bfriendId\"\x17\n" +
	"\x15ContactDeleteResponse\"3\n" +
	"\x14ContactDetailRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x05R\bfriendId\"\x81\x02\n" +
	"\x15ContactDetailResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05motto\x18\x05 \x01(\tR\x05motto\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x1a\n" +
	"\brelation\x18\a \x01(\x05R\brelation\x12\x19\n" +
	"\bgroup_id\x18\b \x01(\x05R\agroupId\x12\x1a\n" +
	"\bbirthday\x18\t \x01(\tR\bbirthday\"0\n" +
	"\x14ContactSearchRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"\xf2\x01\n" +
	"\x15ContactSearchResponse\x129\n" +
	"\x05items\x18\x01 \x03(\v2#.contact.ContactSearchResponse.ItemR\x05items\x1a\x9d\x01\n" +
	"\x04Item\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x05 \x01(\x05R\x06gender\x12\x14\n" +
	"\x05motto\x18\x06 \x01(\tR\x05motto\"S\n" +
	"\x19ContactChangeGroupRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x05R\bfriendId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x05R\agroupId\"\x1c\n" +
	"\x1aContactChangeGroupResponse\"L\n" +
	"\x13ContactApplyRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x05R\bfriendId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14ContactApplyResponse\"0\n" +
	"\x13ContactAgreeRequest\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x05R\aapplyId\"\x16\n" +
	"\x14ContactAgreeResponse\"I\n" +
	"\x14ContactRejectRequest\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x05R\aapplyId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\"\x17\n" +
	"\x15ContactRejectResponse\"\x19\n" +
	"\x17ContactApplyListRequest\"\xa3\x02\n" +
	"\x18ContactApplyListResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.contact.ContactApplyListResponse.ItemR\x05items\x1a\xc8\x01\n" +
	"\x04Item\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\x05R\aapplyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x03 \x01(\x05R\bfriendId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"apply_time\x18\a \x01(\tR\tapplyTime\"\x1b\n" +
	"\x19ContactApplyUnreadRequest\"2\n" +
	"\x1aContactApplyUnreadResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"/\n" +
	"\x19ContactGroupCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"7\n" +
	"\x1aContactGroupCreateResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"J\n" +
	"\x19ContactGroupUpdateRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1c\n" +
	"\x1aContactGroupUpdateResponse\"6\n" +
	"\x19ContactGroupDeleteRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"\x1c\n" +
	"\x1aContactGroupDeleteResponse\"\x19\n" +
	"\x17ContactGroupListRequest\"\xa5\x01\n" +
	"\x18ContactGroupListResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.contact.ContactGroupListResponse.ItemR\x05items\x1aK\n" +
	"\x04Item\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"6\n" +
	"\x19ContactGroupDetailRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\"\xa0\x01\n" +
	"\x1aContactGroupDetailResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x05R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12=\n" +
	"\bcontacts\x18\x04 \x03(\v2!.contact.ContactListResponse.ItemR\bcontacts2\xb7\t\n" +
	"\x0eContactService\x12A\n" +
	"\x04List\x12\x1b.contact.ContactListRequest\x1a\x1c.contact.ContactListResponse\x12G\n" +
	"\x06Delete\x12\x1d.contact.ContactDeleteRequest\x1a\x1e.contact.ContactDeleteResponse\x12G\n" +
	"\x06Detail\x12\x1d.contact.ContactDetailRequest\x1a\x1e.contact.ContactDetailResponse\x12G\n" +
	"\x06Search\x12\x1d.contact.ContactSearchRequest\x1a\x1e.contact.ContactSearchResponse\x12V\n" +
	"\vChangeGroup\x12\".contact.ContactChangeGroupRequest\x1a#.contact.ContactChangeGroupResponse\x12D\n" +
	"\x05Apply\x12\x1c.contact.ContactApplyRequest\x1a\x1d.contact.ContactApplyResponse\x12D\n" +
	"\x05Agree\x12\x1c.contact.ContactAgreeRequest\x1a\x1d.contact.ContactAgreeResponse\x12G\n" +
	"\x06Reject\x12\x1d.contact.ContactRejectRequest\x1a\x1e.contact.ContactRejectResponse\x12P\n" +
	"\tApplyList\x12 .contact.ContactApplyListRequest\x1a!.contact.ContactApplyListResponse\x12V\n" +
	"\vApplyUnread\x12\".contact.ContactApplyUnreadRequest\x1a#.contact.ContactApplyUnreadResponse\x12V\n" +
	"\vGroupCreate\x12\".contact.ContactGroupCreateRequest\x1a#.contact.ContactGroupCreateResponse\x12V\n" +
	"\vGroupUpdate\x12\".contact.ContactGroupUpdateRequest\x1a#.contact.ContactGroupUpdateResponse\x12V\n" +
	"\vGroupDelete\x12\".contact.ContactGroupDeleteRequest\x1a#.contact.ContactGroupDeleteResponse\x12P\n" +
	"\tGroupList\x12 .contact.ContactGroupListRequest\x1a!.contact.ContactGroupListResponse\x12V\n" +
	"\vGroupDetail\x12\".contact.ContactGroupDetailRequest\x1a#.contact.ContactGroupDetailResponseB\vZ\t./contactb\x06proto3"

var (
	file_idl_contact_contact_proto_rawDescOnce sync.Once
	file_idl_contact_contact_proto_rawDescData []byte
)

func file_idl_contact_contact_proto_rawDescGZIP() []byte {
	file_idl_contact_contact_proto_rawDescOnce.Do(func() {
		file_idl_contact_contact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_contact_contact_proto_rawDesc), len(file_idl_contact_contact_proto_rawDesc)))
	})
	return file_idl_contact_contact_proto_rawDescData
}

var file_idl_contact_contact_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_idl_contact_contact_proto_goTypes = []any{
	(*ContactListRequest)(nil),            // 0: contact.ContactListRequest
	(*ContactListResponse)(nil),           // 1: contact.ContactListResponse
	(*ContactDeleteRequest)(nil),          // 2: contact.ContactDeleteRequest
	(*ContactDeleteResponse)(nil),         // 3: contact.ContactDeleteResponse
	(*ContactDetailRequest)(nil),          // 4: contact.ContactDetailRequest
	(*ContactDetailResponse)(nil),         // 5: contact.ContactDetailResponse
	(*ContactSearchRequest)(nil),          // 6: contact.ContactSearchRequest
	(*ContactSearchResponse)(nil),         // 7: contact.ContactSearchResponse
	(*ContactChangeGroupRequest)(nil),     // 8: contact.ContactChangeGroupRequest
	(*ContactChangeGroupResponse)(nil),    // 9: contact.ContactChangeGroupResponse
	(*ContactApplyRequest)(nil),           // 10: contact.ContactApplyRequest
	(*ContactApplyResponse)(nil),          // 11: contact.ContactApplyResponse
	(*ContactAgreeRequest)(nil),           // 12: contact.ContactAgreeRequest
	(*ContactAgreeResponse)(nil),          // 13: contact.ContactAgreeResponse
	(*ContactRejectRequest)(nil),          // 14: contact.ContactRejectRequest
	(*ContactRejectResponse)(nil),         // 15: contact.ContactRejectResponse
	(*ContactApplyListRequest)(nil),       // 16: contact.ContactApplyListRequest
	(*ContactApplyListResponse)(nil),      // 17: contact.ContactApplyListResponse
	(*ContactApplyUnreadRequest)(nil),     // 18: contact.ContactApplyUnreadRequest
	(*ContactApplyUnreadResponse)(nil),    // 19: contact.ContactApplyUnreadResponse
	(*ContactGroupCreateRequest)(nil),     // 20: contact.ContactGroupCreateRequest
	(*ContactGroupCreateResponse)(nil),    // 21: contact.ContactGroupCreateResponse
	(*ContactGroupUpdateRequest)(nil),     // 22: contact.ContactGroupUpdateRequest
	(*ContactGroupUpdateResponse)(nil),    // 23: contact.ContactGroupUpdateResponse
	(*ContactGroupDeleteRequest)(nil),     // 24: contact.ContactGroupDeleteRequest
	(*ContactGroupDeleteResponse)(nil),    // 25: contact.ContactGroupDeleteResponse
	(*ContactGroupListRequest)(nil),       // 26: contact.ContactGroupListRequest
	(*ContactGroupListResponse)(nil),      // 27: contact.ContactGroupListResponse
	(*ContactGroupDetailRequest)(nil),     // 28: contact.ContactGroupDetailRequest
	(*ContactGroupDetailResponse)(nil),    // 29: contact.ContactGroupDetailResponse
	(*ContactListResponse_Item)(nil),      // 30: contact.ContactListResponse.Item
	(*ContactSearchResponse_Item)(nil),    // 31: contact.ContactSearchResponse.Item
	(*ContactApplyListResponse_Item)(nil), // 32: contact.ContactApplyListResponse.Item
	(*ContactGroupListResponse_Item)(nil), // 33: contact.ContactGroupListResponse.Item
}
var file_idl_contact_contact_proto_depIdxs = []int32{
	30, // 0: contact.ContactListResponse.items:type_name -> contact.ContactListResponse.Item
	31, // 1: contact.ContactSearchResponse.items:type_name -> contact.ContactSearchResponse.Item
	32, // 2: contact.ContactApplyListResponse.items:type_name -> contact.ContactApplyListResponse.Item
	33, // 3: contact.ContactGroupListResponse.items:type_name -> contact.ContactGroupListResponse.Item
	30, // 4: contact.ContactGroupDetailResponse.contacts:type_name -> contact.ContactListResponse.Item
	0,  // 5: contact.ContactService.List:input_type -> contact.ContactListRequest
	2,  // 6: contact.ContactService.Delete:input_type -> contact.ContactDeleteRequest
	4,  // 7: contact.ContactService.Detail:input_type -> contact.ContactDetailRequest
	6,  // 8: contact.ContactService.Search:input_type -> contact.ContactSearchRequest
	8,  // 9: contact.ContactService.ChangeGroup:input_type -> contact.ContactChangeGroupRequest
	10, // 10: contact.ContactService.Apply:input_type -> contact.ContactApplyRequest
	12, // 11: contact.ContactService.Agree:input_type -> contact.ContactAgreeRequest
	14, // 12: contact.ContactService.Reject:input_type -> contact.ContactRejectRequest
	16, // 13: contact.ContactService.ApplyList:input_type -> contact.ContactApplyListRequest
	18, // 14: contact.ContactService.ApplyUnread:input_type -> contact.ContactApplyUnreadRequest
	20, // 15: contact.ContactService.GroupCreate:input_type -> contact.ContactGroupCreateRequest
	22, // 16: contact.ContactService.GroupUpdate:input_type -> contact.ContactGroupUpdateRequest
	24, // 17: contact.ContactService.GroupDelete:input_type -> contact.ContactGroupDeleteRequest
	26, // 18: contact.ContactService.GroupList:input_type -> contact.ContactGroupListRequest
	28, // 19: contact.ContactService.GroupDetail:input_type -> contact.ContactGroupDetailRequest
	1,  // 20: contact.ContactService.List:output_type -> contact.ContactListResponse
	3,  // 21: contact.ContactService.Delete:output_type -> contact.ContactDeleteResponse
	5,  // 22: contact.ContactService.Detail:output_type -> contact.ContactDetailResponse
	7,  // 23: contact.ContactService.Search:output_type -> contact.ContactSearchResponse
	9,  // 24: contact.ContactService.ChangeGroup:output_type -> contact.ContactChangeGroupResponse
	11, // 25: contact.ContactService.Apply:output_type -> contact.ContactApplyResponse
	13, // 26: contact.ContactService.Agree:output_type -> contact.ContactAgreeResponse
	15, // 27: contact.ContactService.Reject:output_type -> contact.ContactRejectResponse
	17, // 28: contact.ContactService.ApplyList:output_type -> contact.ContactApplyListResponse
	19, // 29: contact.ContactService.ApplyUnread:output_type -> contact.ContactApplyUnreadResponse
	21, // 30: contact.ContactService.GroupCreate:output_type -> contact.ContactGroupCreateResponse
	23, // 31: contact.ContactService.GroupUpdate:output_type -> contact.ContactGroupUpdateResponse
	25, // 32: contact.ContactService.GroupDelete:output_type -> contact.ContactGroupDeleteResponse
	27, // 33: contact.ContactService.GroupList:output_type -> contact.ContactGroupListResponse
	29, // 34: contact.ContactService.GroupDetail:output_type -> contact.ContactGroupDetailResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_idl_contact_contact_proto_init() }
func file_idl_contact_contact_proto_init() {
	if File_idl_contact_contact_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_contact_contact_proto_rawDesc), len(file_idl_contact_contact_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_contact_contact_proto_goTypes,
		DependencyIndexes: file_idl_contact_contact_proto_depIdxs,
		MessageInfos:      file_idl_contact_contact_proto_msgTypes,
	}.Build()
	File_idl_contact_contact_proto = out.File
	file_idl_contact_contact_proto_goTypes = nil
	file_idl_contact_contact_proto_depIdxs = nil
}
