// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: idl/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token 类型
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// token
	AccessToken string `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// 过期时间
	ExpiresIn     int32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_idl_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AccessToken) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AccessToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AccessToken) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 登录接口请求参数
type AuthLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录账号
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 登录密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginRequest) Reset() {
	*x = AuthLoginRequest{}
	mi := &file_idl_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginRequest) ProtoMessage() {}

func (x *AuthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthLoginRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 登录接口响应参数
type AuthLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *AccessToken           `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginResponse) Reset() {
	*x = AuthLoginResponse{}
	mi := &file_idl_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginResponse) ProtoMessage() {}

func (x *AuthLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginResponse.ProtoReflect.Descriptor instead.
func (*AuthLoginResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthLoginResponse) GetAuth() *AccessToken {
	if x != nil {
		return x.Auth
	}
	return nil
}

// 注销登录接口请求参数
type AuthLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogoutRequest) Reset() {
	*x = AuthLogoutRequest{}
	mi := &file_idl_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogoutRequest) ProtoMessage() {}

func (x *AuthLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogoutRequest.ProtoReflect.Descriptor instead.
func (*AuthLogoutRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{3}
}

// 注销登录接口返回参数
type AuthLogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogoutResponse) Reset() {
	*x = AuthLogoutResponse{}
	mi := &file_idl_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogoutResponse) ProtoMessage() {}

func (x *AuthLogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogoutResponse.ProtoReflect.Descriptor instead.
func (*AuthLogoutResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{4}
}

// 刷新Token接口请求参数
type AuthRefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefreshRequest) Reset() {
	*x = AuthRefreshRequest{}
	mi := &file_idl_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshRequest) ProtoMessage() {}

func (x *AuthRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshRequest.ProtoReflect.Descriptor instead.
func (*AuthRefreshRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{5}
}

// 刷新Token接口返回参数
type AuthRefreshResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 授权 token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 过期时间 单位秒
	ExpireIn      int32 `protobuf:"varint,2,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRefreshResponse) Reset() {
	*x = AuthRefreshResponse{}
	mi := &file_idl_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRefreshResponse) ProtoMessage() {}

func (x *AuthRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRefreshResponse.ProtoReflect.Descriptor instead.
func (*AuthRefreshResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *AuthRefreshResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthRefreshResponse) GetExpireIn() int32 {
	if x != nil {
		return x.ExpireIn
	}
	return 0
}

// 注册接口请求参数
type AuthRegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 注册账号
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 注册密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 昵称
	Nickname      string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterRequest) Reset() {
	*x = AuthRegisterRequest{}
	mi := &file_idl_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterRequest) ProtoMessage() {}

func (x *AuthRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterRequest.ProtoReflect.Descriptor instead.
func (*AuthRegisterRequest) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *AuthRegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// 注册接口响应参数
type AuthRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterResponse) Reset() {
	*x = AuthRegisterResponse{}
	mi := &file_idl_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterResponse) ProtoMessage() {}

func (x *AuthRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterResponse.ProtoReflect.Descriptor instead.
func (*AuthRegisterResponse) Descriptor() ([]byte, []int) {
	return file_idl_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *AuthRegisterResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_idl_auth_auth_proto protoreflect.FileDescriptor

const file_idl_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x13idl/auth/auth.proto\x12\x04auth\"c\n" +
	"\vAccessToken\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x05R\texpiresIn\"J\n" +
	"\x10AuthLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\":\n" +
	"\x11AuthLoginResponse\x12%\n" +
	"\x04auth\x18\x01 \x01(\v2\x11.auth.AccessTokenR\x04auth\"\x13\n" +
	"\x11AuthLogoutRequest\"\x14\n" +
	"\x12AuthLogoutResponse\"\x14\n" +
	"\x12AuthRefreshRequest\"H\n" +
	"\x13AuthRefreshResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\texpire_in\x18\x02 \x01(\x05R\bexpireIn\"i\n" +
	"\x13AuthRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"*\n" +
	"\x14AuthRegisterResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code2\x87\x02\n" +
	"\vAuthService\x128\n" +
	"\x05Login\x12\x16.auth.AuthLoginRequest\x1a\x17.auth.AuthLoginResponse\x12;\n" +
	"\x06Logout\x12\x17.auth.AuthLogoutRequest\x1a\x18.auth.AuthLogoutResponse\x12>\n" +
	"\aRefresh\x12\x18.auth.AuthRefreshRequest\x1a\x19.auth.AuthRefreshResponse\x12A\n" +
	"\bRegister\x12\x19.auth.AuthRegisterRequest\x1a\x1a.auth.AuthRegisterResponseB\bZ\x06./authb\x06proto3"

var (
	file_idl_auth_auth_proto_rawDescOnce sync.Once
	file_idl_auth_auth_proto_rawDescData []byte
)

func file_idl_auth_auth_proto_rawDescGZIP() []byte {
	file_idl_auth_auth_proto_rawDescOnce.Do(func() {
		file_idl_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_auth_auth_proto_rawDesc), len(file_idl_auth_auth_proto_rawDesc)))
	})
	return file_idl_auth_auth_proto_rawDescData
}

var file_idl_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_idl_auth_auth_proto_goTypes = []any{
	(*AccessToken)(nil),          // 0: auth.AccessToken
	(*AuthLoginRequest)(nil),     // 1: auth.AuthLoginRequest
	(*AuthLoginResponse)(nil),    // 2: auth.AuthLoginResponse
	(*AuthLogoutRequest)(nil),    // 3: auth.AuthLogoutRequest
	(*AuthLogoutResponse)(nil),   // 4: auth.AuthLogoutResponse
	(*AuthRefreshRequest)(nil),   // 5: auth.AuthRefreshRequest
	(*AuthRefreshResponse)(nil),  // 6: auth.AuthRefreshResponse
	(*AuthRegisterRequest)(nil),  // 7: auth.AuthRegisterRequest
	(*AuthRegisterResponse)(nil), // 8: auth.AuthRegisterResponse
}
var file_idl_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthLoginResponse.auth:type_name -> auth.AccessToken
	1, // 1: auth.AuthService.Login:input_type -> auth.AuthLoginRequest
	3, // 2: auth.AuthService.Logout:input_type -> auth.AuthLogoutRequest
	5, // 3: auth.AuthService.Refresh:input_type -> auth.AuthRefreshRequest
	7, // 4: auth.AuthService.Register:input_type -> auth.AuthRegisterRequest
	2, // 5: auth.AuthService.Login:output_type -> auth.AuthLoginResponse
	4, // 6: auth.AuthService.Logout:output_type -> auth.AuthLogoutResponse
	6, // 7: auth.AuthService.Refresh:output_type -> auth.AuthRefreshResponse
	8, // 8: auth.AuthService.Register:output_type -> auth.AuthRegisterResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_idl_auth_auth_proto_init() }
func file_idl_auth_auth_proto_init() {
	if File_idl_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_auth_auth_proto_rawDesc), len(file_idl_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_auth_auth_proto_goTypes,
		DependencyIndexes: file_idl_auth_auth_proto_depIdxs,
		MessageInfos:      file_idl_auth_auth_proto_msgTypes,
	}.Build()
	File_idl_auth_auth_proto = out.File
	file_idl_auth_auth_proto_goTypes = nil
	file_idl_auth_auth_proto_depIdxs = nil
}
